java.compatibility=17
kotlin.compatibility=2.2.0

kdoc.olderVersions=
kdoc.projects=:openfeedback,:openfeedback-m3,:openfeedback-resources,:openfeedback-ui-models,:openfeedback-viewmodel
kdoc.artifactId=kdoc

pom.groupId=io.github.4rthurrousseau
pom.version=1.0.0-alpha.7-SNAPSHOT
pom.description=openfeedback-sdk-kotlin
pom.vcsUrl=https://github.com/4rthurrousseau/openfeedback-sdk-kotlin
pom.developer=openfeedback-sdk-kotlin authors
pom.license=MIT License

# https://github.com/GradleUp/tapmoc/issues/82
checkDependenciesCompatibility=false