java.compatibility=17
kotlin.compatibility=2.0.0

kdoc.olderVersions=
kdoc.artifactId=kdoc

pom.groupId=io.github.4rthurrousseau
pom.version=1.0.0-alpha.8
pom.description=openfeedback-sdk-kotlin
pom.vcsUrl=https://github.com/4rthurrousseau/openfeedback-sdk-kotlin
pom.developer=openfeedback-sdk-kotlin authors
pom.license=MIT License
